name = "PolyhedralTypes"
uuid = "04466376-f0d4-4dcb-9501-6d23e2ffd3ed"
authors = ["Kemal Rose <krose@mis.mpg.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Polymake = "d720cf60-89b5-51f5-aff5-213f193123e7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
